AI_MARK = "X"
ALL_MATCHES = '_all_matchs'
ANIMAL = 'animal_'
ANIMALS = 'animals'
ANSI_GOLD = "\033[38;2;255;215;0m"
ANSI_AQUAMARINE = "\033[38;2;102;205;170m"   # Color used to highlight ranking table columns       
ANSI_POS_NEUTRAL = "\033[38;2;160;160;160m"  # Light neutral gray
BLACK = 'black'
BLUE = 'blue'
BOARD = 'board'
BOLD = 'bold'
BUTTONS = 'buttons'
BUTTONS_PANEL = 'button_panel'
CHECKBUTTON = '_check_btn'
COLOR = 'color_'
COLOR_BG_DEFAULT = 'gray13'
COLOR_BOARD_BUTTON_FRAMES = "#37d3ff"
COLOR_BOX_CREDENTIALS = 'aquamarine2'
COLOR_CENTER_HIGHLIGHT = 'darkorchid1'
COLOR_DISPLAY_TEXT = 'gold3'
COLOR_EASY_LEVEL = 'limegreen'
COLOR_HARD_LEVEL = 'red'
COLOR_HIGHLIGHT = 'orange'
COLOR_HIGHLIGHT_TEXT_CREDENTIALS = 'gold3'
COLOR_HIGHLIGHT_DEFAULT = "gray"
COLOR_HIGHLIGHT_SIZE_RADIOBUTTONS = 'darkgoldenrod3'
COLOR_HIGHLIGHT_WIN = 'red'
COLOR_MEDIUM_LEVEL = 'gold1'
COLOR_OPPONENT_SCORE = 'red'
COLOR_PLAYER_SCORE = 'limegreen'
COLOR_SELECTOR = 'gray30'
COLOR_SIZE_RADIOBUTTONS = 'aquamarine2'
COLOR_TIED_GAME = '#d4d4d4'
COLOR_VERY_HARD_LEVEL = 'purple1'
COLORS = 'colors'
CONFIGURATION_PANEL = 'configuration_panel'
DARK = 'DARK'
DEFAULT_GAMES = '000'
DEFAULT_SCORE = '000'
DEFAULT_WINS = '00'
DIFFICULTY_PANEL = 'difficulty_panel'
DIGITAL_STYLE = 'ds-digital'
DISPLAY = 'display'
EASY = 'EASY'
EMPTY = ""
EMPTY_CELL = ""
FIRST_ANIMAL = 'animal_1'
FIRST_COLOR = 'color_1'
FIRST_USER = 'username_1'
FONT_FAMILY_DEFAULT = 'Arial'
FONT_SIZE_LARGE = 40
FONT_SIZE_MEDIUM = 14
FONT_SIZE_SMALL = 10
FONT_DISPLAY = (FONT_FAMILY_DEFAULT, FONT_SIZE_MEDIUM, BOLD)
FONT_SMALL_BOLD = (FONT_FAMILY_DEFAULT, FONT_SIZE_SMALL, BOLD)
FONT_MEDIUM_BOLD = (FONT_FAMILY_DEFAULT, 12, BOLD)
FONT_LARGE_BOLD = (FONT_FAMILY_DEFAULT, FONT_SIZE_LARGE, BOLD)
FRAME = '_frame'
GAMES = 'GAMES'
GRAY = 'gray'
HARD = 'HARD'
LABEL = '_label'
LAST = '_last'
LIGHT = 'LIGHT'
LIST = '_list'
LOGS = {
    'BOTH': 'both',
    'CONSOLE': 'console',
    'FILE': 'file'
}
MACHINE = 'MACHINE'
MAX_LENGHT = 20
MEDIUM = 'MEDIUM'
MOVE = 'move'
NAME = 'name'
NUM_PLAYERS = 2
PANEL = 'panel'
POS = 'POS'
PLAYER_MARK = "O"
PYPE = '|'
RADIOBUTTON = '_radio_btn_'
RATE = 'RATE'
RESET = 'RESET'
RESET_COLOR = '\033[0m'
SCORE = 'SCORE'
SECOND_ANIMAL = 'animal_2'
SECOND_COLOR = 'color_2'
SECOND_USER = 'username_2'
SELECT = '_select'
SELECT_ANIMAL = 'SELECT ANIMAL:'
SELECT_COLOR = 'SELECT COLOR:'
SIZE_BOARD = 3
SLIDER_STYLE = 'TScale'
SPACE = " "
START = 'START'
TEXT_BOARD_SIZE_DIMENSION = 'BOARD SIZE DIMENSION'
TEXT_DIFFICULTY_LEVEL = 'SELECT DIFFICULTY LEVEL'
TEXT_EASY_LEVEL = (
    "YOU PLAY AGAINST\n"
    "A RANDOM MACHINE\n"
    "WITH NEITHER\n"
    "STRATEGY NOR IA"
)

TEXT_MEDIUM_LEVEL = (
    "YOU PLAY AGAINST\n"
    "A BASIC AI USING\n"
    "MINIMAX WITH\n"
    "SOME RANDOM ERRORS"
)

TEXT_HARD_LEVEL = (
    "YOU PLAY AGAINST\n"
    "A LOGICAL AI USING\n"
    "MINIMAX + PRUNING\n"
    "NO HEURISTIC BOOSTS"
)

TEXT_VERY_HARD_LEVEL = (
    "YOU PLAY AGAINST\n"
    "A PRO AI USING\n"
    "ADVANCED MINIMAX\n"
    "HEURISTICS + MEMORY"
)
TEXT_MACHINE_TURN = 'MACHINE is thinking\nnext move...'
TEXT_MOVE_SCALE = "MOVE\nTHE\nSCALE"
TEXT_PLAY_VS_MACHINE = "PLAY VS MACHINE"
TEXT_EXIT_BUTTON = "❌ EXIT"
TEXT_RESET_BUTTON = "🔄 RESET"
TEXT_START_BUTTON = "▶ START"
TEXT_START_CREDENTIALS = "PLEASE ENTER THE CREDENTIALS OF THE USERS OF THE TIC-TAC-TOE GAME"
TEXT_START_THE_GAME = 'Press the START button\nto begin the game 😎'
TEXT_START_NEW_GAME = 'Press the START button\nto begin a new game 😎'
TEXT_TIED_GAME = 'The game has ended in a draw \nand both players get 1 point 🤝'
TEXT_WINS_THE_GAME = ' has won\nthe game! 😎 and get 3 POINTS'
TIED = 'tied'
UNDERSCORE = '_'
USER = 'USER'
USERNAME_COLON = 'USERNAME:'
USERNAME = 'username_'
USERNAMES = 'usernames'
USER_PLAYER = 'user_player_'
VERY_HARD = 'VERY_HARD'
WHITE = 'white'
WIDGET = 'widget'
WHOLE = 'whole'
WINNER = 'winner'
WINS = 'WINS'
WRITE = 'write'
